---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - containerd
    state: present

- name: Create the containerd folder in /etc.
  file:
    path: /etc/containerd
    state: directory

- name: Generate a containerd config.
  shell: containerd config default > /etc/containerd/config.toml
  notify: restart containerd

- include_tasks: crictl.yml